// Code generated by fyne-theme-generator

package main

import (
	"image/color"

	"fyne.io/fyne"
	"fyne.io/fyne/theme"
)

type myTheme struct{}

func (myTheme) BackgroundColor() color.Color { return color.RGBA{R: 0xff, G: 0xff, B: 0xff, A: 0xff} }
func (myTheme) ButtonColor() color.Color     { return color.Alpha16{A: 0x0} }
func (myTheme) DisabledButtonColor() color.Color {
	return color.RGBA{R: 0xe5, G: 0xe5, B: 0xe5, A: 0xff}
}
func (myTheme) TextColor() color.Color            { return color.RGBA{R: 0x21, G: 0x21, B: 0x21, A: 0xff} }
func (myTheme) DisabledTextColor() color.Color    { return color.RGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x42} }
func (myTheme) IconColor() color.Color            { return color.RGBA{R: 0x21, G: 0x21, B: 0x21, A: 0xff} }
func (myTheme) DisabledIconColor() color.Color    { return color.RGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x42} }
func (myTheme) HyperlinkColor() color.Color       { return color.RGBA{R: 0x2e, G: 0x85, B: 0x55, A: 0xff} }
func (myTheme) PlaceHolderColor() color.Color     { return color.RGBA{R: 0x88, G: 0x88, B: 0x88, A: 0xff} }
func (myTheme) PrimaryColor() color.Color         { return color.RGBA{R: 0x2e, G: 0x85, B: 0x55, A: 0xff} }
func (myTheme) HoverColor() color.Color           { return color.RGBA{R: 0x0, G: 0x0, B: 0x0, A: 0xf} }
func (myTheme) FocusColor() color.Color           { return color.RGBA{R: 0x2e, G: 0x85, B: 0x55, A: 0xff} }
func (myTheme) ScrollBarColor() color.Color       { return color.NRGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x99} }
func (myTheme) ShadowColor() color.Color          { return color.RGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x33} }
func (myTheme) TextSize() int                     { return 14 }
func (myTheme) TextFont() fyne.Resource           { return theme.LightTheme().TextFont() }
func (myTheme) TextBoldFont() fyne.Resource       { return theme.LightTheme().TextBoldFont() }
func (myTheme) TextItalicFont() fyne.Resource     { return theme.LightTheme().TextItalicFont() }
func (myTheme) TextBoldItalicFont() fyne.Resource { return theme.LightTheme().TextBoldItalicFont() }
func (myTheme) TextMonospaceFont() fyne.Resource  { return theme.LightTheme().TextMonospaceFont() }
func (myTheme) Padding() int                      { return 4 }
func (myTheme) IconInlineSize() int               { return 20 }
func (myTheme) ScrollBarSize() int                { return 16 }
func (myTheme) ScrollBarSmallSize() int           { return 3 }
